sudo: required
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build --stacktrace