sudo: required
language: android
jdk: oraclejdk8
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - sys-img-x86-google_apis-27
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - openssl aes-256-cbc
    -K $encrypted_ffed81facfa0_key
    -iv $encrypted_ffed81facfa0_iv
    -in ./app/google-services.json.enc
    -out ./app/google-services.json -d
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;29.0.0"
before_script:
  - echo avdmanager list target
  - echo no | avdmanager create avd --force -n test -k "system-images;android-27;google_apis;x86" -c 100M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew build --stacktrace
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"