sudo: required
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;29.0.0"
script:
  - ./gradlew build --stacktrace
