sudo: required
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script:
  - openssl aes-256-cbc
    -K $encrypted_ffed81facfa0_key
    -iv $encrypted_ffed81facfa0_iv
    -in ./app/google-services.json.enc
    -out ./app/google-services.json -d
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;29.0.0"
script:
  - ./gradlew build --stacktrace
